# Generated by Django 4.1.3 on 2022-12-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="sex",
            field=models.CharField(
                choices=[
                    ("female", "Female"),
                    ("male", "Male"),
                    ("Not informed", "Default"),
                ],
                default="Not informed",
                max_length=20,
            ),
        ),
    ]
