# Generated by Django 4.1.3 on 2022-12-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0002_alter_pet_sex"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="sex",
            field=models.CharField(
                choices=[
                    ("Female", "Female"),
                    ("Male", "Male"),
                    ("Not informed", "Default"),
                ],
                default="Not informed",
                max_length=20,
            ),
        ),
    ]
